name: static check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  static-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.13'
          cache: true

      - name: Install dependencies
        run: pdm install
      
      - name: Run static checks
        run: pdm run tox -e static_check
